/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:get/get.dart';
import 'package:get/get_core/src/get_interface.dart';

extension FontWeightExtension on FontWeight {
  FontWeight get auto {
    if (Platform.isAndroid && this == FontWeight.bold) {
      return FontWeight.w500;
    }
    return this;
  }
}
extension HexColor on String {
  /// String is in the format "aabbcc" or "ffaabbcc" with an optional leading "#".
  Color toColor() {
    if (this.length >3) {
      final buffer = StringBuffer();
      if (this.length == 6 || this.length == 7) buffer.write('ff');
      buffer.write(this.replaceFirst('#', ''));
      return Color(int.parse(buffer.toString(), radix: 16));
    }
    return Colors.white;
  }

/// Prefixes a hash sign if [leadingHashSign] is set to `true` (default is `true`).

}

extension DarkMode on BuildContext {
  /// is dark mode currently enabled?
  bool get isDarkMode {
    final brightness = MediaQuery.of(this).platformBrightness;
    return brightness == Brightness.dark;
  }
}

extension Loc on GetInterface {
  /// is dark mode currently enabled?
  bool get isLocEnglish {
  
    return Get.locale!.languageCode.toString().contains("en");
  }
}