/// Generated by Flutter GetX Starter on 2022-09-05 15:53

import 'package:flutter/cupertino.dart';
import 'package:get/get_navigation/src/routes/get_route.dart';

import '../pages/splash/view.dart';


class PageRoutes {
  static const SPLASH = '/Splash';


  static List<GetPage> routes = [
    GetPage(
      name: PageRoutes.SPLASH,
      page: () => SplashPage(),
    ),

  ];
}

class ServerRoute {
  static const SIGNIN = 'general/signin';

}
