/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:sizer/sizer.dart';

class Constant {
  static List months = [
    'jan',
    'feb',
    'mar',
    'april',
    'may',
    'jun',
    'july',
    'aug',
    'sep',
    'oct',
    'nov',
    'dec'
  ];

  static bool isTabletMode = SizerUtil.deviceType == DeviceType.tablet;
  static String HTTP_HOST ="asd";

  static Map<String, dynamic> parseUrlScheme(String url) {
    Uri uri = Uri.parse(url);
    Map<String, dynamic> result = {};

    String appname = "";
    if (uri.scheme == appname &&
        uri.host == "${appname.contains("mbin") ? "mobin" : "mobin"}.app") {
      Map<String, String> queryParams = uri.queryParameters;

      if (queryParams.containsKey("token")) {
        result["token"] = queryParams["token"];
      }

      if (queryParams.containsKey("loginResults")) {
        result["loginResults"] = queryParams["loginResults"] == "true";
      }
    }

    return result;
  }


  static debugLog(String log){
   if(kDebugMode) print('Constant.debugLog = ${log}');
  }

}
const MESSAGE_SEPARATOR = '@';

/// 设计图尺寸用于屏幕适配
class Design {
  static double width = 750;
  static double height = 1334;
}

class GetRtlWidget extends StatelessWidget {
  final Widget child;

  const GetRtlWidget({required this.child}) : super();

  @override
  Widget build(BuildContext context) {
    return Directionality(textDirection: TextDirection.rtl, child: this.child);
    return child;
  }
}

class GetLTRWidget extends StatelessWidget {
  final Widget child;

  const GetLTRWidget({required this.child}) : super();

  @override
  Widget build(BuildContext context) {
    return Directionality(textDirection: TextDirection.ltr, child: this.child);
    return child;
  }
}
