import 'package:mediaverse/flavors.dart';

class AppIcon {
  static String  assetTitle = '${F.assetTitle}/icons';
  static String videoIcon = 'assets/${assetTitle}/video.svg';
  static String imageIcon = 'assets/${assetTitle}/image.svg';
  static String soundIcon = 'assets/${assetTitle}/sound.svg';
  static String textIcon = 'assets/${assetTitle}/text.svg';
  static String searchIcon = 'assets/${assetTitle}/search.svg';
  static String musicIcon = 'assets/${assetTitle}/music.svg';
  static String profileIcon = 'assets/${assetTitle}/profile.svg';
  static String exploreIcon = 'assets/${assetTitle}/explore.svg';
  static String walletIcon = 'assets/${assetTitle}/wallet.svg';
  static String addIcon = 'assets/${assetTitle}/add.svg';
  static String deviceIcon = 'assets/${assetTitle}/device.svg';
  static String closeIcon = 'assets/${assetTitle}/close.svg';
  static String downIcon = 'assets/${assetTitle}/down.svg';
  static String upIcon = 'assets/${assetTitle}/up.svg';
  static String detail1Icon = 'assets/${assetTitle}/detail1.svg';
  static String detail2Icon = 'assets/${assetTitle}/detail2.svg';
  static String detail3Icon = 'assets/${assetTitle}/detail3.svg';
  static String detail4Icon = 'assets/${assetTitle}/detail4.svg';
  static String channelIcon = 'assets/${assetTitle}/channel.svg';
  static String walletdeIcon = 'assets/${assetTitle}/walletde.svg';
  static String profiledeIcon = 'assets/${assetTitle}/profilede.svg';
  static String channeldeIcon = 'assets/${assetTitle}/channelde.svg';
  static String exploredeIcon = 'assets/${assetTitle}/explorede.svg';
  static String chipIcon = 'assets/${assetTitle}/Chip.svg';
  static String cardIcon = 'assets/${assetTitle}/card.svg';
  static String mastercardIcon = 'assets/${assetTitle}/mastercard.svg';
  static String settingIcon = 'assets/${assetTitle}/setting.svg';
  static String backIcon = 'assets/${assetTitle}/back.svg';
  static String emailIcon = 'assets/${assetTitle}/email.svg';
  static String analyticsIcon = 'assets/${assetTitle}/Analytics.svg';
  static String shareIcon = 'assets/${assetTitle}/share.svg';
  static String wallet1Icon = 'assets/${assetTitle}/wallet1.svg';
  static String account1Icon = 'assets/${assetTitle}/account1.svg';
  static String playIcon = 'assets/${assetTitle}/play.svg';
  static String addImageIcon = 'assets/${assetTitle}/addImage.png';
  static String boxcircleIcon = 'assets/${assetTitle}/boxcircle.svg';
  static String uploadIcon = 'assets/${assetTitle}/upload.svg';
  static String saveIcon = 'assets/${assetTitle}/save.svg';
  static String fullscreenIcon = 'assets/${assetTitle}/fullscreen.png';
  static String screenshotIcon = 'assets/${assetTitle}/screenshot.png';
  static String recIcon = 'assets/${assetTitle}/rec.png';
  static String recActiveIcon = 'assets/${assetTitle}/recActive.png';
  static String liveIcon = 'assets/${assetTitle}/live.svg';
}
