/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:sizer/sizer.dart';

import 'app_color.dart';

class Constant {

  static showMessege(String mseeges){
    ScaffoldMessenger.of(Get.context!).showSnackBar(SnackBar(content: Text(mseeges,
      style: TextStyle(color: AppColor.primaryDarkColor),)));
  }

  static List<String> languages = [
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian",
    "Azerbaijani",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Cebuano",
    "Chichewa",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Corsican",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Esperanto",
    "Estonian",
    "Filipino",
    "Finnish",
    "French",
    "Frisian",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hawaiian",
    "Hebrew",
    "Hindi",
    "Hmong",
    "Hungarian",
    "Icelandic",
    "Igbo",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kazakh",
    "Khmer",
    "Kinyarwanda",
    "Korean",
    "Kurdish (Kurmanji)",
    "Kyrgyz",
    "Lao",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Maori",
    "Marathi",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Odia (Oriya)",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Samoan",
    "Scots Gaelic",
    "Serbian",
    "Sesotho",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swedish",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Turkish",
    "Turkmen",
    "Ukrainian",
    "Urdu",
    "Uyghur",
    "Uzbek",
    "Vietnamese",
    "Welsh",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zulu",
  ];

  static List months = [
    'jan',
    'feb',
    'mar',
    'april',
    'may',
    'jun',
    'july',
    'aug',
    'sep',
    'oct',
    'nov',
    'dec'
  ];

  static bool isTabletMode = SizerUtil.deviceType == DeviceType.tablet;
  static String HTTP_HOST ="https://api.mediaverse.studio/v2/";

  static Map<String, dynamic> parseUrlScheme(String url) {
    Uri uri = Uri.parse(url);
    Map<String, dynamic> result = {};

    String appname = "";
    if (uri.scheme == appname &&
        uri.host == "${appname.contains("mbin") ? "mobin" : "mobin"}.app") {
      Map<String, String> queryParams = uri.queryParameters;

      if (queryParams.containsKey("token")) {
        result["token"] = queryParams["token"];
      }

      if (queryParams.containsKey("loginResults")) {
        result["loginResults"] = queryParams["loginResults"] == "true";
      }
    }

    return result;
  }


  static debugLog(String log){
   if(kDebugMode) print('Constant.debugLog = $log');
  }

}
const MESSAGE_SEPARATOR = '@';

/// 设计图尺寸用于屏幕适配
class Design {
  static double width = 750;
  static double height = 1334;
}

class GetRtlWidget extends StatelessWidget {
  final Widget child;

  const GetRtlWidget({super.key, required this.child});

  @override
  Widget build(BuildContext context) {
    return Directionality(textDirection: TextDirection.rtl, child: child);
    return child;
  }
}

class GetLTRWidget extends StatelessWidget {
  final Widget child;

  const GetLTRWidget({super.key, required this.child});

  @override
  Widget build(BuildContext context) {
    return Directionality(textDirection: TextDirection.ltr, child: child);
    return child;
  }
}
