/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'dart:convert';
import 'dart:developer' as developer;

import 'package:flutter/foundation.dart';

class Logger {
  static String tag = "Logger";
  static bool isLogEnable = true;
  static bool isDebugEnable = true;



}